name: Build and Push Images
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to in-cluster Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push demo-app
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/procinger/active-user-app:latest
            ghcr.io/procinger/active-user-app:1.${{ github.run_number }}.${{ github.run_attempt }}
          cache-from: type=registry,ref=ghcr.io/procinger/active-user-app:latest
          cache-to: type=inline
          platforms: linux/amd64,linux/arm64
          push: true
